name: Indicate your project is participating in Dev Days
description: | 
  For hosted projects only, use this form to indicate that your project will be participating in Dev Days.
title: "Dev Days 2024 Project Application - PROJECTNAME"
labels: ["help wanted"]
assignees: 
  - yarille
  - jmertic
  - carolalynn
  - lgritz
body:
  - type: markdown
    attributes:
      value: |
        ![](https://artwork.aswf.io/other/dev-days/2024/color/dev-days-2024-color.svg)

        Thank you for your interest in being a project wanting to participate in Dev Days 2024!
        For hosted projects only, use this form to indicate that your project will be participating in Dev Days.

        Please update `PROJECTNAME` in the title with your project name.
  - type: input
    attributes:
      label: URL to your Dev Days 2024 landing page
      description: |
        This URL can be a webpage, wiki page, or file in your code repository, that outlines...
    validations:
      required: true
  - type: input
    attributes:
      label: URL of issues for participants to work on
      description: |
        Projects should label issues with 'good first issue' and 'help wanted', and ensure 
        that they are unassigned and no more than one year old. To validate, go to 
        [CLOTributor](https://clotributor.dev/search?foundation=aswf&good_first_issue=true).

        These issues should align with the Academy Software Foundation TAC's
        [best practices for good first issues]()
    validations:
      required: true
  - type: textarea
    attributes:
      label: Communication channel(s) for partipants
      description: |
        What are the best communications channel(s) for Dev Days particpants to use? This is
        likely your primary Slack channel or mailing list, but you could also setup a seperate
        communication channel if that would be preferred.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Project meeting(s) for Dev Days partipants to join
      description: |
        What project meeting(s) should a potential Dev Days participant join if they want to 
        work with your project during Dev Days? This might be one of the project's
        regular TSC meetings, or could be separate meeting(s).
      validation:
        required: true
  - type: input
    attributes:
      label: URL to the project "Getting Started" and build instructions
      description: |
        Indicate the URL where your project has instructions for Dev Days participants
        to set up thier development environment and instructions for building the project.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected time commitments for participants
      description: |
        What should Dev Days partipants for the project expect in terms of time commitments? Note
        that it's expected that each of the issues might have varying time commitments, but giving
        a general sense can be helpful.
    validations:
      required: true
