name: Update Data From LFX
on:
  issues:
    types:
      - "labeled"
      - "unlabeled"
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jmertic/lfx-tac-actions@693b9f0cdf3798e25e01d19b5c7f2fb2f4d94b27 # 2024-11-14
        with:
          landscape_url: https://aswf.landscape2.io
          artwork_url: https://artwork.aswf.io 
          lfx_tac_committee_url: https://projectadmin.lfx.linuxfoundation.org/project/a09410000182dD2AAI/collaboration/committees/81ed2abc-d041-495b-be89-0dffedf8ce85
          tac_agenda_gh_project_url: https://github.com/orgs/AcademySoftwareFoundation/projects/19 
        env:
          token: ${{ secrets.PAT }} 
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
