name: Update Data Sources
on:
  issues:
    types:
      - "labeled"
      - "unlabeled"
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit

    - name: Check out repo
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Set up Python 3.x
      uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
      with:
        python-version: '3.x'
    - name: Run build
      run: |
        python .github/workflows/updateprojects.py
        python .github/workflows/updatetacmembers.py
        python .github/workflows/updatetacagendaitems.py
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
      with:
         token: ${{ secrets.PAT }}
         branch-suffix: timestamp
         path: .
         title: Update Data Sources
         labels: automerge
         commit-message: Update Data Sources
         signoff: true
