name: Update Data Sources
on:
  issues:
    types:
      - "labeled"
      - "unlabeled"
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - name: Check out repo
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Set up Python 3.x
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: '3.x'
    - name: Run build
      run: |
        python .github/workflows/updateprojects.py
        python .github/workflows/updatetacmembers.py
        python .github/workflows/updatetacagendaitems.py
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6.0.5
      with:
         token: ${{ secrets.PAT }}
         branch-suffix: timestamp
         path: .
         title: Update Data Sources
         labels: automerge
         commit-message: Update Data Sources
         signoff: true
