name: Update TAC members
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Grab latest TAC member list
      uses: gautemo/fetch-api-data-action@1.0.2
      with:
         url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRZnU6dlt-5jIdwfyv1H30S7irc9u1LS1VO0qgxrU7kEUCJBeh9Rk-5EeIZfCq_PUGdAzSe_gMxNycF/pub?gid=2056721984&single=true&output=csv'
         file: '_data/tacmembers.csv'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
         token: ${{ secrets.PAT }}
         branch-suffix: timestamp
         path: .
         title: Update TAC members
         labels: automated-build
         commit-message: Update TAC members

